/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedCareerOptionsRouteImport } from './routes/_authenticated/career-options'
import { Route as AuthenticatedCareerSuggesterRouteImport } from './routes/_authenticated/career-suggester'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFollowUpRouteImport } from './routes/_authenticated/follow-up'
import { Route as AuthenticatedGapsRouteImport } from './routes/_authenticated/gaps'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInterviewIndexRouteImport } from './routes/_authenticated/interview.index'
import { Route as AuthenticatedInterviewJobIdRouteImport } from './routes/_authenticated/interview.$jobId'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedApplyJobIdIndexRouteImport } from './routes/_authenticated/apply.$jobId.index'
import { Route as AuthenticatedApplyJobIdReviewRouteImport } from './routes/_authenticated/apply.$jobId.review'
import { Route as AuthenticatedApplyJobIdSubmitRouteImport } from './routes/_authenticated/apply.$jobId.submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCareerOptionsRoute =
  AuthenticatedCareerOptionsRouteImport.update({
    id: '/career-options',
    path: '/career-options',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareerSuggesterRoute =
  AuthenticatedCareerSuggesterRouteImport.update({
    id: '/career-suggester',
    path: '/career-suggester',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpRoute = AuthenticatedFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGapsRoute = AuthenticatedGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewIndexRoute =
  AuthenticatedInterviewIndexRouteImport.update({
    id: '/interview/',
    path: '/interview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewJobIdRoute =
  AuthenticatedInterviewJobIdRouteImport.update({
    id: '/interview/$jobId',
    path: '/interview/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyJobIdIndexRoute =
  AuthenticatedApplyJobIdIndexRouteImport.update({
    id: '/apply/$jobId/',
    path: '/apply/$jobId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplyJobIdReviewRoute =
  AuthenticatedApplyJobIdReviewRouteImport.update({
    id: '/apply/$jobId/review',
    path: '/apply/$jobId/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplyJobIdSubmitRoute =
  AuthenticatedApplyJobIdSubmitRouteImport.update({
    id: '/apply/$jobId/submit',
    path: '/apply/$jobId/submit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/career-options': typeof AuthenticatedCareerOptionsRoute
  '/career-suggester': typeof AuthenticatedCareerSuggesterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/interview/$jobId': typeof AuthenticatedInterviewJobIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/interview/': typeof AuthenticatedInterviewIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/apply/$jobId/review': typeof AuthenticatedApplyJobIdReviewRoute
  '/apply/$jobId/submit': typeof AuthenticatedApplyJobIdSubmitRoute
  '/apply/$jobId/': typeof AuthenticatedApplyJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/career-options': typeof AuthenticatedCareerOptionsRoute
  '/career-suggester': typeof AuthenticatedCareerSuggesterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/follow-up': typeof AuthenticatedFollowUpRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/interview/$jobId': typeof AuthenticatedInterviewJobIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/interview': typeof AuthenticatedInterviewIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/apply/$jobId/review': typeof AuthenticatedApplyJobIdReviewRoute
  '/apply/$jobId/submit': typeof AuthenticatedApplyJobIdSubmitRoute
  '/apply/$jobId': typeof AuthenticatedApplyJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/career-options': typeof AuthenticatedCareerOptionsRoute
  '/_authenticated/career-suggester': typeof AuthenticatedCareerSuggesterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/follow-up': typeof AuthenticatedFollowUpRoute
  '/_authenticated/gaps': typeof AuthenticatedGapsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/interview/$jobId': typeof AuthenticatedInterviewJobIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/interview/': typeof AuthenticatedInterviewIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/apply/$jobId/review': typeof AuthenticatedApplyJobIdReviewRoute
  '/_authenticated/apply/$jobId/submit': typeof AuthenticatedApplyJobIdSubmitRoute
  '/_authenticated/apply/$jobId/': typeof AuthenticatedApplyJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/career-options'
    | '/career-suggester'
    | '/dashboard'
    | '/follow-up'
    | '/gaps'
    | '/profile'
    | '/interview/$jobId'
    | '/jobs/$id'
    | '/interview/'
    | '/jobs/'
    | '/apply/$jobId/review'
    | '/apply/$jobId/submit'
    | '/apply/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/career-options'
    | '/career-suggester'
    | '/dashboard'
    | '/follow-up'
    | '/gaps'
    | '/profile'
    | '/interview/$jobId'
    | '/jobs/$id'
    | '/interview'
    | '/jobs'
    | '/apply/$jobId/review'
    | '/apply/$jobId/submit'
    | '/apply/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/career-options'
    | '/_authenticated/career-suggester'
    | '/_authenticated/dashboard'
    | '/_authenticated/follow-up'
    | '/_authenticated/gaps'
    | '/_authenticated/profile'
    | '/_authenticated/interview/$jobId'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/interview/'
    | '/_authenticated/jobs/'
    | '/_authenticated/apply/$jobId/review'
    | '/_authenticated/apply/$jobId/submit'
    | '/_authenticated/apply/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/career-options': {
      id: '/_authenticated/career-options'
      path: '/career-options'
      fullPath: '/career-options'
      preLoaderRoute: typeof AuthenticatedCareerOptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-suggester': {
      id: '/_authenticated/career-suggester'
      path: '/career-suggester'
      fullPath: '/career-suggester'
      preLoaderRoute: typeof AuthenticatedCareerSuggesterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-up': {
      id: '/_authenticated/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof AuthenticatedFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gaps': {
      id: '/_authenticated/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AuthenticatedGapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/': {
      id: '/_authenticated/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof AuthenticatedInterviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$jobId': {
      id: '/_authenticated/interview/$jobId'
      path: '/interview/$jobId'
      fullPath: '/interview/$jobId'
      preLoaderRoute: typeof AuthenticatedInterviewJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$jobId/': {
      id: '/_authenticated/apply/$jobId/'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId/'
      preLoaderRoute: typeof AuthenticatedApplyJobIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$jobId/review': {
      id: '/_authenticated/apply/$jobId/review'
      path: '/apply/$jobId/review'
      fullPath: '/apply/$jobId/review'
      preLoaderRoute: typeof AuthenticatedApplyJobIdReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$jobId/submit': {
      id: '/_authenticated/apply/$jobId/submit'
      path: '/apply/$jobId/submit'
      fullPath: '/apply/$jobId/submit'
      preLoaderRoute: typeof AuthenticatedApplyJobIdSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCareerOptionsRoute: typeof AuthenticatedCareerOptionsRoute
  AuthenticatedCareerSuggesterRoute: typeof AuthenticatedCareerSuggesterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowUpRoute: typeof AuthenticatedFollowUpRoute
  AuthenticatedGapsRoute: typeof AuthenticatedGapsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedInterviewJobIdRoute: typeof AuthenticatedInterviewJobIdRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
  AuthenticatedInterviewIndexRoute: typeof AuthenticatedInterviewIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedApplyJobIdReviewRoute: typeof AuthenticatedApplyJobIdReviewRoute
  AuthenticatedApplyJobIdSubmitRoute: typeof AuthenticatedApplyJobIdSubmitRoute
  AuthenticatedApplyJobIdIndexRoute: typeof AuthenticatedApplyJobIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCareerOptionsRoute: AuthenticatedCareerOptionsRoute,
  AuthenticatedCareerSuggesterRoute: AuthenticatedCareerSuggesterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowUpRoute: AuthenticatedFollowUpRoute,
  AuthenticatedGapsRoute: AuthenticatedGapsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedInterviewJobIdRoute: AuthenticatedInterviewJobIdRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
  AuthenticatedInterviewIndexRoute: AuthenticatedInterviewIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedApplyJobIdReviewRoute: AuthenticatedApplyJobIdReviewRoute,
  AuthenticatedApplyJobIdSubmitRoute: AuthenticatedApplyJobIdSubmitRoute,
  AuthenticatedApplyJobIdIndexRoute: AuthenticatedApplyJobIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
